### ISSUE TITLE
Support for 2.0.{4,5}

### ISSUE THREAD

**Issue by dbuenzli** [dbuenzli/tsdl#23]
Go through the [release notes](http://hg.libsdl.org/SDL/file/9dad1513547b/WhatsNew.txt) and add bindings to the new entry points and enumerants.

**Comment by eriklovlie** [comment]
I've added https://wiki.libsdl.org/SDL_QueueAudio?highlight=%28%5CbCategoryAPI%5Cb%29%7C%28SDLFunctionTemplate%29 in my pinned tsdl. I'm not an advanced ocaml user and I'm certainly not sure I grok all the ctypes stuff but it Seems To Work (tm). If I also add this to `test_audio.ml` will you accept a pull request?

**Comment by dbuenzli** [comment]
Please do and I will review it. Do however provide the test in another `test_audio_queue.ml` file.

**Comment by Octachron** [comment]
Since SDL 2.06.0 introduced Vulkan support that I am quite interested in, I have been trying my hand at adding support for the new 2.04.0-to-2.06.0 SDL features in `tsdl`.

A point that I am uncertain right now is that this Vulkan support requires access to two vulkan types `VkInstance` and `VkSurfaceKHR`. I am currently inclined to have a small library that provides these two types to both `tsdl` and potential vulkan libraries rather than adding mere abstract types to `tsdl`.

Do you have any opinion/advice on this matter?

**Comment by dbuenzli** [comment]
If those are pointer then I'd rather do this via `unsafe` functions to `nativeint` see e.g. [here]( https://github.com/dbuenzli/tsdl/blob/5eea7734424c3a19ddc8cb7b840b63a1987338c2/src/tsdl.mli#L319-L325).

**Comment by Octachron** [comment]
`VkSurfaceKHR` is 64 bits integer handle rather than a pointer, but the same point apply. Ok for adding conversion function to nativeint (for VkInstance) or uint64 .

**Comment by dbuenzli** [comment]
This has been solved by @octachron even up to 2.0.6. Thanks.
