### ISSUE TITLE
allow refinement of Event enums

### ISSUE THREAD

**Issue by sanette** [dbuenzli/tsdl#53]
SDL allows to create new event types, so maybe it would make sense to allow for refinement of the Event type enum. That is, write

```
 val enum : event_type ->
    [> `App_did_enter_background | `App_did_enter_foreground
    | `App_low_memory | `App_terminating | `App_will_enter_background
(etc)
```
In this case one could easily expand the enum function to return new variant tags like `My_new_event

**Comment by dbuenzli** [comment]
The problem is that doing this by default can lead to wild type error messages. I think it would be better to *name* the variants cases with a type i.e. have `type enum = ...`. Once this is done it becomes easier to write open coercions and/or "open" functions `enum -> [> enum]`.

I don't have much time to invest in `tsdl` these days. PRs are welcome.
